### PR TITLE
Add labeled Mockup in Part 2

### PR DESCRIPTION
**Pull request by laney0808**
Fix issue #27

### CODE REVIEW

**Comment by laney0808** [comment]
Request to change: The structure is lacking a VBox inside the ScrollPane.

**Comment by damithc** [comment]
> Request to change: The structure is lacking a VBox inside the ScrollPane.

@laney0808 can you elaborate?

**Comment by laney0808** [comment]
> > Request to change: The structure is lacking a VBox inside the ScrollPane.
> 
> @laney0808 can you elaborate?

Hi Prof! I added this comment because I realized the new graph is lacking a label on the VBox. I'll add it in the next commit.

**Comment by laney0808** [comment]
> I like how this provides a clear idea of what the hierarchy graph will look like. Is `Input` one of the nodes too, or do you think it can be removed to avoid confusion? Perhaps something like this? I believe that's the text in the original UI. Sure! let's change it to the new version to avoid confusion.

**Comment by laney0808** [comment]
Requested change completed.

**Comment by JiaXinEu** [comment]
LGTM!

**Pull request merged**
